# Generated by Django 5.2 on 2025-04-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
        ('users', '0002_location_name_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacetransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_transactions', to='users.employerprofile'),
        ),
    ]
