# Generated by Django 5.2 on 2025-04-22 14:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_transactionnotification'),
        ('users', '0004_merge_20250422_1904'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacetransaction',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='transactionnotification',
            name='notification_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('offer', 'Offer'), ('status_change', 'Status Change'), ('other', 'Other')], default='other', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketoffer',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 14, 18, 42, 742091, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketoffer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketoffer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketplacetransaction',
            name='admin_approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketplacetransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_transactions', to='users.employerprofile'),
        ),
        migrations.AlterField(
            model_name='marketplacetransaction',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='marketplace.marketoffer'),
        ),
        migrations.AlterField(
            model_name='marketplacetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketplacetransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionnotification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.marketplacetransaction'),
        ),
        migrations.AlterField(
            model_name='transactionnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeCreditOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('buy', 'Buy Credits'), ('sell', 'Sell Credits')], max_length=4)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_rate', models.DecimalField(decimal_places=2, help_text='Current market rate when offer was created', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total dollar amount of the transaction', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_offers', to='users.employeeprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_credit_offers', to='users.employerprofile')),
            ],
        ),
    ]
