# Generated by Django 5.2 on 2025-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_marketplacetransaction_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecreditoffer',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional information for redemption requests', null=True),
        ),
        migrations.AlterField(
            model_name='employeecreditoffer',
            name='offer_type',
            field=models.CharField(choices=[('buy', 'Buy Credits'), ('sell', 'Sell Credits'), ('redeem', 'Redeem Credits')], max_length=10),
        ),
    ]
