// Minimal browser-side inference over responses using a simple linear model
// Weights are produced by a training script and saved as weights.json:
// {
//   "classes": ["Normal","Protanopia","Deuteranopia","Tritanopia"],
//   "W": [[...],[...],...], // shape: num_classes x num_features
//   "b": [...]
// }

// Settings for the test flow
const SETTINGS = {
  MAX_PLATES: 12,                   // exactly 12 plates per test session
  UNIQUE_PER_PLATE_TYPE: true,      // keep at most one image per (plate_id, type_idx)
  BALANCE_BY_TYPE: true,            // aim for a balance across type_idx
  BALANCE_BY_THEME: true,           // attempt to include varied themes/colors
};

const state = {
  manifest: [],
  idx: -1,
  responses: [], // {plate_id, type_idx(gt if known), answer}
  weights: null,
  sessionId: null,
};

async function requestGeneratedPlate(idx){
  const type_idx = 1 + (idx % 3);
  // Generate random 2-digit numbers only (10-99)
  const numeral = 10 + Math.floor(Math.random() * 90);
  const plate_id = 1000 + idx;
  // Use consistent parameters for all plates
  const payload = { plate_id, type_idx, numeral };
  const res = await fetch('/next-plate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });
  if(!res.ok) throw new Error('Generator endpoint failed');
  return res.json();
}

function shuffleInPlace(arr){
  for(let i = arr.length - 1; i > 0; i--){
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
}

function groupBy(arr, key){
  const m = new Map();
  for(const it of arr){
    const k = key(it);
    const v = m.get(k);
    if(v) v.push(it); else m.set(k, [it]);
  }
  return m;
}

function pickBalancedByTheme(candidates, max){
  if(!SETTINGS.BALANCE_BY_THEME) return candidates.slice(0, max);
  const byTheme = groupBy(candidates, it => it.theme || 'unknown');
  const themes = Array.from(byTheme.keys());
  shuffleInPlace(themes);
  const out = [];
  while(out.length < max){
    let added = false;
    for(const th of themes){
      const arr = byTheme.get(th);
      if(!arr || arr.length === 0) continue;
      out.push(arr.pop());
      added = true;
      if(out.length >= max) break;
    }
    if(!added) break;
  }
  return out;
}

async function loadManifest(){
  // plates_manifest.json is generated by scripts/build_manifest.py --copy-web web/
  const res = await fetch('plates_manifest.json');
  if(!res.ok) throw new Error('Missing plates_manifest.json. Run build_manifest.py with --copy-web web/.');
  let data = await res.json();

  // Optional: reduce to one image per (plate_id, type_idx)
  if (SETTINGS.UNIQUE_PER_PLATE_TYPE){
    const seen = new Set();
    data = data.filter(item => {
      const key = `${item.plate_id}::${item.type_idx}`;
      if(seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }

  // Shuffle order to avoid any bias from filename sorting
  shuffleInPlace(data);

  // Balance by type if requested
  if (SETTINGS.BALANCE_BY_TYPE){
    const g = groupBy(data, it => it.type_idx);
    const types = Array.from(g.keys());
    const per = Math.max(1, Math.floor(SETTINGS.MAX_PLATES / Math.max(1, types.length)));
    let picked = [];
    for(const t of types){
      const arr = g.get(t);
      shuffleInPlace(arr);
      // diversify by theme within type
      picked = picked.concat(pickBalancedByTheme(arr, per));
    }
    // If under MAX_PLATES, top up from leftovers
    shuffleInPlace(data);
    const setPaths = new Set(picked.map(x => x.path));
    for(const it of data){
      if(picked.length >= SETTINGS.MAX_PLATES) break;
      if(!setPaths.has(it.path)) picked.push(it);
    }
    data = picked;
  }
  // Enforce cap again
  if (SETTINGS.MAX_PLATES && data.length > SETTINGS.MAX_PLATES) data = data.slice(0, SETTINGS.MAX_PLATES);
  // Final shuffle to avoid any residual ordering (e.g., by type or theme)
  shuffleInPlace(data);

  state.manifest = data;
  document.getElementById('loadedCount').textContent = String(state.manifest.length);
  // Allow starting even if no manifest; generator will synthesize plates on demand
  document.getElementById('startBtn').disabled = false;
  const prog = document.getElementById('progressLabel');
  if (prog) prog.textContent = `0/${state.manifest.length}`;
}

function showPlate(){
  if(state.idx < 0 || state.idx >= state.manifest.length) return;
  const item = state.manifest[state.idx];
  const img = document.getElementById('plateImg');
  img.src = item.path;
  const numeralPart = (item && item.numeral != null) ? `  numeral=${item.numeral}` : '';
  const themePart = item.theme ? `  theme=${item.theme}` : '';
  document.getElementById('plateInfo').textContent = `#${item.plate_id}  type=${item.type_idx}${numeralPart}${themePart}`;
  
  // Image loaded successfully
  img.onload = () => {
    console.log('Plate image loaded:', item.path);
  };
}

function nextPlate(){
  state.idx += 1;
  if(state.idx >= state.manifest.length){
    // Test session complete - exactly 12 plates have been shown
    const img = document.getElementById('plateImg');
    if (img) img.removeAttribute('src');
    document.getElementById('plateInfo').textContent = '-';
    document.getElementById('resultBox').textContent = 'Session complete. Click Predict for results.';
    document.getElementById('nextBtn').disabled = true;
    document.getElementById('predictBtn').disabled = false;
    const prog = document.getElementById('progressLabel');
    if (prog) prog.textContent = `${state.manifest.length}/${state.manifest.length}`;
    return;
  }
  showPlate();
  const prog = document.getElementById('progressLabel');
  if (prog) prog.textContent = `${state.idx}/${state.manifest.length}`;
}

function reset(){
  state.idx = -1;
  state.responses = [];
  const img = document.getElementById('plateImg');
  if (img) img.removeAttribute('src');
  document.getElementById('plateInfo').textContent = '-';
  document.getElementById('resultBox').textContent = 'No prediction yet.';
  document.getElementById('predictBtn').disabled = true;
  const prog = document.getElementById('progressLabel');
  if (prog) prog.textContent = `0/${state.manifest.length || 0}`;
}

function makeFeatureVector(weights, manifest, responses){
  // Build features to match weights.feature schema
  const schema = (weights && weights.feature) || {};
  const weightPlateIds = Array.isArray(schema.plate_ids) ? schema.plate_ids.slice() : [...new Set(manifest.map(m => m.plate_id))].sort((a,b)=>a-b);
  const idIndex = new Map(weightPlateIds.map((id,i)=>[id,i]));
  const answerDim = Number.isFinite(schema.answer_dim) ? schema.answer_dim : 100;
  const extraTypeDim = Number.isFinite(schema.extra_type_dim) ? schema.extra_type_dim : 0;

  const featLen = weightPlateIds.length + answerDim + extraTypeDim;
  const feat = new Array(featLen).fill(0);

  for(const r of responses){
    const p = idIndex.get(r.plate_id);
    if(p != null) feat[p] = 1;
    const ansIdx = Math.max(0, Math.min(answerDim-1, parseInt(r.answer || '0', 10)));
    feat[weightPlateIds.length + ansIdx] = 1;
    // Optional extra type features: map type_idx (1..3) to 0..2
    if(extraTypeDim >= 3 && Number.isFinite(r.type_idx)){
      const t = Math.max(1, Math.min(3, parseInt(r.type_idx, 10))) - 1;
      feat[weightPlateIds.length + answerDim + t] = 1;
    }
  }
  return feat;
}

function softmax(z){
  const safe = z.map(v => Number.isFinite(v) ? v : -1e9);
  const m = Math.max(...safe);
  const exps = safe.map(v=>Math.exp(v - m));
  let s = exps.reduce((a,b)=>a+b,0);
  if(!Number.isFinite(s) || s === 0) s = 1;
  return exps.map(v=>v/s);
}

function predict(weights, features){
  const { classes, W, b } = weights;
  const logits = W.map((row, i)=> {
    let acc = Number.isFinite(b[i]) ? b[i] : 0;
    const L = Math.min(row.length, features.length);
    for(let j=0;j<L;j++){
      const wj = Number.isFinite(row[j]) ? row[j] : 0;
      const fj = Number.isFinite(features[j]) ? features[j] : 0;
      acc += wj * fj;
    }
    return acc;
  });
  const probs = softmax(logits);
  let top = 0; for(let i=1;i<probs.length;i++) if(probs[i] > probs[top]) top = i;
  
  // Healthcare confidence validation
  const maxProb = Math.max(...probs);
  const confidence = maxProb;
  
  // If confidence is too low, flag for manual review
  const isConfident = confidence > 0.7; // 70% confidence threshold for healthcare
  
  return { 
    label: classes[top], 
    probs, 
    confidence: confidence,
    isConfident: isConfident,
    warning: !isConfident ? "Low confidence - Manual review recommended" : null
  };
}

function heuristicProbsFromResponses(responses, classes){
  const C = classes.length;
  const score = new Array(C).fill(1e-6);
  const classIndex = new Map(classes.map((c,i)=>[c,i]));
  const normalIdx = classIndex.get('Normal') ?? 0;
  let wrongCount = 0, total = 0;
  for(const r of responses){
    const expected = (r && r.expected != null) ? String(r.expected) : null;
    if(expected == null) continue;
    const ans = String(r.answer ?? '');
    const wrong = ans !== expected;
    const typeIdx = Math.max(1, Math.min(3, parseInt(r.type_idx, 10) || 1));
    const clsIdx = typeIdx;
    if(wrong){
      score[clsIdx] += 1.0;
      score[normalIdx] += 0.1;
      wrongCount += 1;
    }else{
      score[normalIdx] += 1.0;
      score[clsIdx] += 0.1;
    }
    total += 1;
  }
  const s = score.reduce((a,b)=>a+b,0) || 1;
  const probs = score.map(v=>v/s);
  return { probs, wrongFrac: total ? wrongCount/total : 0 };
}

function blendProbs(pModel, pHeu, alpha){
  const eps = 1e-9;
  const logP = pModel.map((pm,i)=> Math.log((pm || eps)) * (1 - alpha) + Math.log(((pHeu && pHeu[i]) || eps)) * alpha);
  const maxL = Math.max(...logP);
  const exps = logP.map(v=>Math.exp(v - maxL));
  const Z = exps.reduce((a,b)=>a+b,0) || 1;
  return exps.map(v=>v/Z);
}

async function loadWeights(){
  // Try weights.json next to this file. You can replace with your trained weights.
  const res = await fetch('weights.json');
  if(!res.ok) throw new Error('weights.json not found. Train and export weights.');
  return res.json();
}

function showResult(res){
  const lines = [];
  lines.push(`Prediction: ${res.label}`);
  lines.push('Class probabilities:');
  const { classes } = state.weights;
  for(let i=0;i<classes.length;i++){
    lines.push(`- ${classes[i]}: ${(res.probs[i]*100).toFixed(1)}%`);
  }
  
  // Improved severity proxy: use top class probability
  const topProb = Math.max(...res.probs);
  let sev = 'Mild';
  if(topProb > 0.75) sev = 'Severe'; else if(topProb > 0.55) sev = 'Moderate';
  lines.push(`Severity (proxy): ${sev}`);
  
  document.getElementById('resultBox').textContent = lines.join('\n');
}

function addResponse(answer){
  if(state.idx < 0 || state.idx >= state.manifest.length) return;
  const item = state.manifest[state.idx];
  state.responses.push({ numeral: item.numeral, type_idx: item.type_idx, answer, expected: item && item.numeral });
  document.getElementById('predictBtn').disabled = state.responses.length === 0;
}

function setup(){
  const loadBtn = document.getElementById('loadBtn');
  const startBtn = document.getElementById('startBtn');
  const nextBtn = document.getElementById('nextBtn');
  const predictBtn = document.getElementById('predictBtn');
  const responseInput = document.getElementById('responseInput');

  const focusInput = ()=> {
    // keep focus on the input field for fast typing
    setTimeout(()=> { responseInput.focus(); responseInput.select(); }, 0);
  };

  loadBtn.addEventListener('click', ()=> loadManifest().catch(err=> alert(err.message)));
  startBtn.addEventListener('click', async ()=>{
    state.idx = -1;
    state.responses = [];
    state.sessionId = `sess_${Date.now()}_${Math.floor(Math.random()*1e6)}`;
    nextBtn.disabled = false;
    
    // Generate exactly 12 plates for the test session
    try{
      state.manifest = [];
      for(let i = 0; i < SETTINGS.MAX_PLATES; i++){
        const item = await requestGeneratedPlate(i);
        state.manifest.push(item);
      }
      document.getElementById('loadedCount').textContent = String(state.manifest.length);
      const prog = document.getElementById('progressLabel');
      if (prog) prog.textContent = `0/${state.manifest.length}`;
      nextPlate();
      focusInput();
    }catch(e){
      document.getElementById('resultBox').textContent = 'Could not generate plates. Ensure server is running.';
    }
  });
  nextBtn.addEventListener('click', ()=>{
    const ans = responseInput.value.trim();
    if(ans) addResponse(ans);
    responseInput.value='';
    nextPlate();
    focusInput();
  });
  // Submit answer with Enter key and advance to next plate
  responseInput.addEventListener('keydown', (e)=>{
    if(e.key === 'Enter'){
      e.preventDefault();
      const ans = responseInput.value.trim();
      if(ans) addResponse(ans);
      responseInput.value='';
      nextPlate();
      focusInput();
    }
  });
  predictBtn.addEventListener('click', async ()=>{
    try{
      const used = state.responses.slice();
      if(used.length === 0){ alert('No responses recorded yet.'); return; }
      // 1) Append current session responses first (so CSV is updated even if weights are missing)
      try{
        const sid = state.sessionId || '';
        const rows = used.map(r => `${r.numeral},${r.type_idx},${r.answer}`);
        const resp = await fetch('/append-responses', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ rows, session_id: sid })
        });
        if(!resp.ok){ throw new Error('append failed'); }
        state.responses = [];
      }catch(e){
        alert('Could not save responses automatically. Please run start_server.bat and open http://localhost:8000/test.html');
      }
      // 2) Try prediction if weights are available
      try{
        if(!state.weights) state.weights = await loadWeights();
        const feats = makeFeatureVector(state.weights, state.manifest, used);
        const modelRes = predict(state.weights, feats);
        const { probs: heuProbs, wrongFrac } = heuristicProbsFromResponses(used, state.weights.classes);
        // Stronger influence from heuristic when many answers are wrong
        const alpha = Math.min(0.95, 0.3 + 0.7 * wrongFrac);
        let blended = blendProbs(modelRes.probs, heuProbs, alpha);
        // If majority wrong and heuristic disagrees with Normal, trust heuristic fully
        const normalIdx = state.weights.classes.indexOf('Normal');
        let heuTop = 0; for(let i=1;i<heuProbs.length;i++) if(heuProbs[i] > heuProbs[heuTop]) heuTop = i;
        if(wrongFrac >= 0.6 && heuTop !== normalIdx){
          blended = heuProbs.slice();
        }
        const best = blended.indexOf(Math.max(...blended));
        const final = { label: state.weights.classes[best], probs: blended };
        showResult(final);
        // Log final result
        try{
          const sid = state.sessionId || '';
          await fetch('/append-result', {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ session_id: sid, label: final.label, probs: final.probs, total: used.length })
          });
        }catch(_e){ /* ignore */ }
      }catch(_predictErr){
        // weights.json likely missing; non-fatal for CSV append
        document.getElementById('resultBox').textContent = 'Responses saved. Train weights.json to enable prediction.';
      }
    }catch(err){ alert(err.message); }
  });
  document.getElementById('resetBtn').addEventListener('click', reset);

  // Removed export button; prediction will handle appending responses
}

if (typeof document !== 'undefined'){
  document.addEventListener('DOMContentLoaded', setup);
}


