# Generated by Django 5.2 on 2025-04-12 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_type', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10)),
                ('owner_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('transport_mode', models.CharField(choices=[('car', 'Car (Single Occupancy)'), ('carpool', 'Carpool'), ('public_transport', 'Public Transport'), ('bicycle', 'Bicycle'), ('walking', 'Walking'), ('work_from_home', 'Work From Home')], max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbon_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credits_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='trip_proofs/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
