# Generated by Django 5.2 on 2025-04-12 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_ends', to='users.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_starts', to='users.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carboncredit',
            name='source_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_credits', to='trips.trip'),
        ),
    ]
