# Generated by Django 5.2 on 2025-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated travel time in minutes based on transport mode and distance', null=True),
        ),
    ]
