# Generated by Django 5.2 on 2025-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='aqi_level',
            field=models.CharField(blank=True, choices=[('hazardous', 'Hazardous (>300)'), ('very_poor', 'Very Poor (201-300)'), ('moderate', 'Moderate (101-200)'), ('good', 'Good (<100)')], default='moderate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='calculation_method',
            field=models.CharField(blank=True, choices=[('formula', 'Formula-based'), ('ml', 'ML Prediction'), ('hybrid', 'Hybrid (ML + Formula)')], default='formula', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='carbon_credits_earned',
            field=models.FloatField(blank=True, help_text='Carbon credits earned (kg CO₂) - calculated using formula or ML', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='context_factor',
            field=models.FloatField(blank=True, help_text='Context factor (Weather × Route × AQI × Load × Seasonal)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='ef_actual',
            field=models.FloatField(blank=True, help_text='Actual emission factor (kg CO₂/km)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='ef_baseline',
            field=models.FloatField(blank=True, help_text='Baseline emission factor (kg CO₂/km)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='emission_difference',
            field=models.FloatField(blank=True, help_text='Emission difference (kg CO₂/km)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='ml_prediction_confidence',
            field=models.FloatField(blank=True, help_text='ML model prediction confidence (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_type',
            field=models.CharField(blank=True, choices=[('hilly', 'Hilly/Uphill'), ('city_center', 'City Center'), ('highway', 'Highway'), ('suburban', 'Suburban')], default='suburban', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='season',
            field=models.CharField(blank=True, default='normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='time_period',
            field=models.CharField(blank=True, choices=[('peak_morning', 'Peak Morning (7-10 AM)'), ('peak_evening', 'Peak Evening (6-9 PM)'), ('off_peak', 'Off-Peak'), ('late_night', 'Late Night (11 PM - 5 AM)')], default='off_peak', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='time_weight',
            field=models.FloatField(blank=True, help_text='Time weight factor', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='traffic_condition',
            field=models.CharField(blank=True, choices=[('heavy', 'Heavy'), ('moderate', 'Moderate'), ('light', 'Light')], default='moderate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('heavy_rain', 'Heavy Rain'), ('light_rain', 'Light Rain'), ('normal', 'Normal'), ('favorable', 'Favorable')], default='normal', max_length=20, null=True),
        ),
    ]
