# Generated by Django 5.2 on 2025-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_aqi_level_trip_calculation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'Winter'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('post_monsoon', 'Post-Monsoon')], default='post_monsoon', max_length=20, null=True),
        ),
    ]
