# Generated by Django 5.2.7 on 2025-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferide_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='violation',
            name='frame_image',
            field=models.ImageField(upload_to='violation_frames'),
        ),
    ]
