# Generated by Django 5.2.7 on 2025-10-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferide_backend', '0003_alter_violation_labels_violation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='license_plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_plates'),
        ),
        migrations.AddField(
            model_name='violation',
            name='license_plate_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='ocr_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='violation',
            name='ocr_method',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(max_length=50),
        ),
    ]
