# -*- coding: utf-8 -*-
"""Market_Trend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4kUi06AJWOCdVa-16KGT3crXaXWIB1V

**NEW FILE **
"""

import os
import glob
import pandas as pd
import numpy as np


_YEARLY_DF = None


def _find_excel_path() -> str:
    """
    Try to locate the market trend Excel file in common locations and
    with common names (with or without (2), xlsx/xls, root or dataset/).
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))

    # Explicit common filenames first
    candidates = [
        os.path.join(base_dir, "market_trend_all(2).xlsx"),
        os.path.join(base_dir, "market_trend_all.xlsx"),
        os.path.join(base_dir, "market_trend_all.xls"),
        os.path.join(base_dir, "dataset", "market_trend_all(2).xlsx"),
        os.path.join(base_dir, "dataset", "market_trend_all.xlsx"),
        os.path.join(base_dir, "dataset", "market_trend_all.xls"),
    ]

    for path in candidates:
        if os.path.exists(path):
            return path

    # Fall back to wildcard search to support names like market_trend_all(2).xlsm etc.
    patterns = [
        os.path.join(base_dir, "market_trend_all*.xls*"),
        os.path.join(base_dir, "dataset", "market_trend_all*.xls*"),
    ]
    for pattern in patterns:
        matches = glob.glob(pattern)
        if matches:
            return matches[0]

    # Nothing found – give a clear message
    raise FileNotFoundError(
        "Market trend Excel file not found. "
        "Please place your file (e.g. 'market_trend_all(2).xlsx') in either the "
        "project root or in a 'dataset' folder inside the project."
    )


def _load_yearly_df():
    """Load and preprocess the Excel dataset once for reuse."""
    global _YEARLY_DF
    if _YEARLY_DF is not None:
        return _YEARLY_DF

    excel_path = _find_excel_path()
    # Use openpyxl explicitly to avoid optional-engine issues
    df = pd.read_excel(excel_path, engine="openpyxl")

    df["Arrival_Date"] = pd.to_datetime(
        df["Arrival_Date"],
        dayfirst=True,
        errors="coerce",
    )

    price_cols = ["Min_Price", "Max_Price", "Modal_Price"]
    for col in price_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna(subset=["Arrival_Date", "Modal_Price"])
    df["Year"] = df["Arrival_Date"].dt.year

    # Keep a recent range
    df = df[(df["Year"] >= 2020) & (df["Year"] <= 2025)]

    yearly_df = (
        df.groupby(["Year", "Commodity", "District"], as_index=False)
        .agg(
            {
                "Min_Price": "mean",
                "Max_Price": "mean",
                "Modal_Price": "mean",
            }
        )
        .sort_values(["Commodity", "District", "Year"])
    )

    _YEARLY_DF = yearly_df
    return yearly_df


def get_filtered_data(crop: str, city: str) -> pd.DataFrame:
    """Return yearly aggregated prices for a given crop and city (district)."""
    yearly_df = _load_yearly_df()
    data = yearly_df[
        (yearly_df["Commodity"].str.lower() == crop.lower())
        & (yearly_df["District"].str.lower() == city.lower())
    ]
    return data


def get_market_trend_summary(crop: str, city: str) -> dict:
    """
    Compute trend data and summary for a given crop and city.

    Returns a dict ready to be sent as JSON.
    """
    data = get_filtered_data(crop, city)
    if data.empty:
        return {
            "has_data": False,
            "message": "No data available for the selected crop and city.",
        }

    data = data.sort_values("Year")

    years = data["Year"].tolist()
    min_prices = data["Min_Price"].round(2).tolist()
    modal_prices = data["Modal_Price"].round(2).tolist()
    max_prices = data["Max_Price"].round(2).tolist()

    avg_sale_price = float(data["Modal_Price"].mean())
    min_price = float(data["Min_Price"].min())
    max_price = float(data["Max_Price"].max())

    start_price = float(data["Modal_Price"].iloc[0])
    end_price = float(data["Modal_Price"].iloc[-1])

    if end_price > start_price * 1.05:
        market_status = "GOOD (Prices are rising steadily)"
        status_icon = "📈"
    elif end_price < start_price * 0.95:
        market_status = "NOT GOOD (Prices are declining)"
        status_icon = "📉"
    else:
        market_status = "MODERATE (Prices are mostly stable)"
        status_icon = "➖"

    avg_spread = float((data["Max_Price"] - data["Min_Price"]).mean())
    volatility = "high" if avg_spread > 200 else "moderate"

    return {
        "has_data": True,
        "crop": crop,
        "city": city,
        "years": years,
        "min_prices": min_prices,
        "modal_prices": modal_prices,
        "max_prices": max_prices,
        "avg_sale_price": round(avg_sale_price, 2),
        "min_price": round(min_price, 2),
        "max_price": round(max_price, 2),
        "market_status": market_status,
        "status_icon": status_icon,
        "avg_spread": round(avg_spread, 2),
        "volatility": volatility,
    }

