# Generated by Django 5.2 on 2025-04-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('commute', 'Commute'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
