# Generated by Django 5.2 on 2025-04-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile_initial_credits_allocated'),
        ('users', '0003_employeeinvitation'),
    ]

    operations = [
    ]
