# Generated by Django 5.2 on 2026-01-20 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        ('users', '0005_employeeprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('co2_kg_per_unit', models.DecimalField(decimal_places=4, help_text='CO2 kg equivalent per unit', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='IPCC 2006', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('heavy_industry', 'Heavy Industry'), ('manufacturing', 'Manufacturing'), ('power_plant', 'Power Plant'), ('chemical', 'Chemical Plant'), ('steel', 'Steel Plant'), ('textile', 'Textile Industry'), ('other', 'Other Industrial')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('emission_intensity', models.DecimalField(decimal_places=4, help_text='CO2 emission intensity in tons per year', max_digits=8)),
                ('operating_hours', models.JSONField(default=dict, help_text="Operating hours {'start': '08:00', 'end': '18:00', 'days': [1,2,3,4,5]}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_savings_kg', models.DecimalField(decimal_places=4, help_text='Carbon savings in kg CO2', max_digits=10)),
                ('equivalent_factory_hours', models.DecimalField(decimal_places=2, help_text='Equivalent factory operation hours offset', max_digits=8)),
                ('trees_planted_equivalent', models.IntegerField(help_text='Number of trees equivalent to the carbon savings')),
                ('cars_off_road_equivalent', models.DecimalField(decimal_places=2, help_text='Number of cars taken off road for a day', max_digits=5)),
                ('calculation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_impacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='PollutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant_type', models.CharField(choices=[('pm25', 'PM2.5'), ('pm10', 'PM10'), ('co', 'Carbon Monoxide'), ('no2', 'Nitrogen Dioxide'), ('so2', 'Sulfur Dioxide'), ('o3', 'Ozone'), ('aqi', 'Air Quality Index')], max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('unit', models.CharField(default='μg/m³', max_length=20)),
                ('aqi_level', models.CharField(choices=[('good', 'Good (0-50)'), ('moderate', 'Moderate (51-100)'), ('unhealthy_sensitive', 'Unhealthy for Sensitive (101-150)'), ('unhealthy', 'Unhealthy (151-200)'), ('very_unhealthy', 'Very Unhealthy (201-300)'), ('hazardous', 'Hazardous (301+)')], default='moderate', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='API', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_data', to='users.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'pollutant_type', '-timestamp'], name='core_pollut_locatio_9bb4f0_idx'), models.Index(fields=['timestamp'], name='core_pollut_timesta_4f231e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPollutionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_pollution', 'High Pollution Alert'), ('industrial_activity', 'Industrial Activity Alert'), ('air_quality', 'Air Quality Warning'), ('health_advisory', 'Health Advisory')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('industrial_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.industrialzone')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_userpo_user_id_12ccc9_idx')],
            },
        ),
    ]
