# Generated by Django 5.2 on 2026-01-20 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_environmentalmetric_industrialzone_pollutionimpact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('special', 'Special')], max_length=10)),
                ('category', models.CharField(choices=[('trips', 'Trips'), ('carbon', 'Carbon Savings'), ('streak', 'Streak'), ('milestone', 'Milestone'), ('community', 'Community'), ('special', 'Special Achievement')], max_length=15)),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('condition_type', models.CharField(choices=[('trips_count', 'Number of Trips'), ('carbon_saved', 'Carbon Saved'), ('streak_days', 'Consecutive Days'), ('special_condition', 'Special Condition')], max_length=20)),
                ('condition_value', models.IntegerField(help_text='Value required to earn this badge')),
                ('points', models.IntegerField(default=10, help_text='Points awarded for this badge')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['badge_type', 'category', 'points'],
            },
        ),
        migrations.CreateModel(
            name='CommunityChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('company', 'Company')], max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_metric', models.CharField(choices=[('carbon_saved', 'Carbon Saved'), ('trips_count', 'Number of Trips'), ('participants', 'Number of Participants')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('reward_points', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reward_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='core.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leaderboard_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all_time', 'All Time')], max_length=10)),
                ('category', models.CharField(choices=[('carbon_saved', 'Carbon Saved'), ('trips_count', 'Number of Trips'), ('badges_count', 'Badges Earned'), ('streak_days', 'Streak Days'), ('points', 'Total Points')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('leaderboard_type', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_value', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.communitychallenge')),
            ],
            options={
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('rank', models.IntegerField()),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.leaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['leaderboard', 'rank'], name='core_leader_leaderb_8e18c0_idx'), models.Index(fields=['user', '-last_updated'], name='core_leader_user_id_1735c1_idx')],
                'unique_together': {('leaderboard', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(choices=[('daily_trips', 'Daily Trips'), ('sustainable_transport', 'Sustainable Transport'), ('carbon_goal', 'Carbon Goal')], max_length=25)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'streak_type')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress_value', models.IntegerField(help_text='Current progress towards badge')),
                ('is_earned', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_type', models.CharField(choices=[('trip', 'Trip Completion'), ('badge', 'Badge Earned'), ('streak', 'Streak Milestone'), ('challenge', 'Challenge Completion'), ('bonus', 'Bonus Points')], max_length=10)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_userpo_user_id_11db21_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_type', models.CharField(choices=[('daily_goal', 'Daily Goal'), ('weekly_goal', 'Weekly Goal'), ('monthly_goal', 'Monthly Goal'), ('badge_progress', 'Badge Progress'), ('streak_progress', 'Streak Progress')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('user', 'progress_type')},
            },
        ),
    ]
