# Generated by Django 5.2 on 2026-02-15 20:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_communitychallenge_leaderboard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('employee', 'Employee Wallet'), ('employer', 'Employer Wallet'), ('system', 'System Wallet')], default='employee', max_length=20)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('frozen_balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Wallet',
                'verbose_name_plural': 'Carbon Wallets',
                'db_table': 'carbon_wallets',
            },
        ),
        migrations.CreateModel(
            name='CreditExpiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('expiry_date', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_records', to='core.carbonwallet')),
            ],
            options={
                'verbose_name': 'Credit Expiry',
                'verbose_name_plural': 'Credit Expiries',
                'db_table': 'credit_expiry',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='core.carbonwallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='core.carbonwallet')),
            ],
            options={
                'verbose_name': 'Credit Transfer',
                'verbose_name_plural': 'Credit Transfers',
                'db_table': 'credit_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_transfer_enabled', models.BooleanField(default=False)),
                ('auto_transfer_threshold', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('low_balance_alert', models.DecimalField(decimal_places=4, default=10.0, max_digits=12)),
                ('monthly_report_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_transfer_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.carbonwallet')),
            ],
            options={
                'verbose_name': 'Wallet Settings',
                'verbose_name_plural': 'Wallet Settings',
                'db_table': 'wallet_settings',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('expiry', 'Expiry'), ('reward', 'Reward'), ('penalty', 'Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source', models.CharField(blank=True, choices=[('trip', 'Trip Activity'), ('transfer', 'Transfer'), ('reward', 'Reward'), ('penalty', 'Penalty'), ('expiry', 'Credit Expiry'), ('system', 'System Adjustment'), ('marketplace', 'Marketplace')], max_length=50, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transaction_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.carbonwallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
